-- Fotos de capa do Wikimedia Commons.
--
-- GERADO por scripts/fotos-de-capa.mjs. Nao editar a mao: rode o script de novo.
--
-- Cada foto vem com autor, licenca e pagina de origem porque CC BY e CC BY-SA
-- OBRIGAM atribuir. Lugar sem credito completo foi descartado pelo script --
-- sem poder creditar, nao ha permissao para publicar.
--
-- 20 de 20 lugares com foto. 0 descartado(s) por credito incompleto.

update places as p set
  cover_image_url     = novo.url,
  cover_image_author  = novo.autor,
  cover_image_license = novo.licenca,
  cover_image_source  = novo.origem
from (values
  ('cascata-do-avencal', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Cascata_do_Avencal_-_Urubici_-_Brasil_%2846134213575%29.jpg/1920px-Cascata_do_Avencal_-_Urubici_-_Brasil_%2846134213575%29.jpg', 'Rosanetur from Rio de Janeiro, Brazil', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Cascata_do_Avencal_-_Urubici_-_Brasil_(46134213575).jpg'),
  ('garopaba', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Rua_dos_Pres%C3%A9pios_-_Garopaba%2C_17.12.2025_03.jpg/1920px-Rua_dos_Pres%C3%A9pios_-_Garopaba%2C_17.12.2025_03.jpg', 'Parzeus', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Rua_dos_Pres%C3%A9pios_-_Garopaba,_17.12.2025_03.jpg'),
  ('guarda-do-embau', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Guarda_do_Emba%C3%BA%2C_Santa_Catarina%2C_Brasil.jpg/1920px-Guarda_do_Emba%C3%BA%2C_Santa_Catarina%2C_Brasil.jpg', 'Rodrigo Soldon', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Guarda_do_Emba%C3%BA,_Santa_Catarina,_Brasil.jpg'),
  ('lagoa-da-conceicao', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Lagoa_da_Concei%C3%A7%C3%A3o_-_Florian%C3%B3polis_%281%29.jpg/1920px-Lagoa_da_Concei%C3%A7%C3%A3o_-_Florian%C3%B3polis_%281%29.jpg', 'Rodrigo.Argenton', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Lagoa_da_Concei%C3%A7%C3%A3o_-_Florian%C3%B3polis_(1).jpg'),
  ('laguna', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Laguna_Miscanti%2C_Chile%2C_2016-02-08%2C_DD_32.JPG/1920px-Laguna_Miscanti%2C_Chile%2C_2016-02-08%2C_DD_32.JPG', 'Diego Delso', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Laguna_Miscanti,_Chile,_2016-02-08,_DD_32.JPG'),
  ('lauro-muller', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Esta%C3%A7%C3%A3o_Ferrovi%C3%A1ria_Lauro_M%C3%BCller_2.jpg/1920px-Esta%C3%A7%C3%A3o_Ferrovi%C3%A1ria_Lauro_M%C3%BCller_2.jpg', 'Kaktus Kid', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Esta%C3%A7%C3%A3o_Ferrovi%C3%A1ria_Lauro_M%C3%BCller_2.jpg'),
  ('morro-da-cruz', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Florian%C3%B3polis_SC_Brasil_-_Vista_do_Centro_Mirante_Morro_da_Cruz_-_panoramio.jpg/1920px-Florian%C3%B3polis_SC_Brasil_-_Vista_do_Centro_Mirante_Morro_da_Cruz_-_panoramio.jpg', 'Josue Marinho', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:Florian%C3%B3polis_SC_Brasil_-_Vista_do_Centro_Mirante_Morro_da_Cruz_-_panoramio.jpg'),
  ('morro-da-igreja', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/MORRO_DA_IGREJA%2C_NA_SERRA_DO_CORVO_BRANCO_EM_URUBICI-SC%2C_BRAZIL_05.jpg/1920px-MORRO_DA_IGREJA%2C_NA_SERRA_DO_CORVO_BRANCO_EM_URUBICI-SC%2C_BRAZIL_05.jpg', 'EDI GALVANI ULIANO', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MORRO_DA_IGREJA,_NA_SERRA_DO_CORVO_BRANCO_EM_URUBICI-SC,_BRAZIL_05.jpg'),
  ('pomerode', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Pomerode_by_Totonho_Barreto_and_K%C3%A1tia_C._Oliveira_08.jpg/1920px-Pomerode_by_Totonho_Barreto_and_K%C3%A1tia_C._Oliveira_08.jpg', 'Ajmcbarreto', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Pomerode_by_Totonho_Barreto_and_K%C3%A1tia_C._Oliveira_08.jpg'),
  ('praia-da-pinheira', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Praia_da_Pinheira_%2814729183250%29.jpg/1920px-Praia_da_Pinheira_%2814729183250%29.jpg', 'Otávio Nogueira from Fortaleza, BR', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Praia_da_Pinheira_(14729183250).jpg'),
  ('praia-do-rosa', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Praia_do_Rosa%2C_Imbutuba%2C_mar%C3%A7o_de_2023_%285%29.jpg/1920px-Praia_do_Rosa%2C_Imbutuba%2C_mar%C3%A7o_de_2023_%285%29.jpg', 'Fronteira', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Praia_do_Rosa,_Imbutuba,_mar%C3%A7o_de_2023_(5).jpg'),
  ('praia-grande', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Playa_de_Praia_da_Vit%C3%B3ria%2C_isla_de_Terceira%2C_Azores%2C_Portugal%2C_2020-07-24%2C_DD_57-65_PAN.jpg/1920px-Playa_de_Praia_da_Vit%C3%B3ria%2C_isla_de_Terceira%2C_Azores%2C_Portugal%2C_2020-07-24%2C_DD_57-65_PAN.jpg', 'Diego Delso', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Playa_de_Praia_da_Vit%C3%B3ria,_isla_de_Terceira,_Azores,_Portugal,_2020-07-24,_DD_57-65_PAN.jpg'),
  ('rancho-queimado', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Rancho_Queimado_%28Rio%29.jpg/1920px-Rancho_Queimado_%28Rio%29.jpg', 'AndreWormsbecker', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Rancho_Queimado_(Rio).jpg'),
  ('santo-amaro-da-imperatriz', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Hotel_Caldas_da_Imperatriz%2C_Santo_Amaro_da_Imperatriz_%28municipality%29%2C_Santa_Catarina_State%2C_Brazil.JPG/1920px-Hotel_Caldas_da_Imperatriz%2C_Santo_Amaro_da_Imperatriz_%28municipality%29%2C_Santa_Catarina_State%2C_Brazil.JPG', 'Eugenio Hansen, OFS', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Hotel_Caldas_da_Imperatriz,_Santo_Amaro_da_Imperatriz_(municipality),_Santa_Catarina_State,_Brazil.JPG'),
  ('sao-joaquim', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/S%C3%A3o_Joaquim_metro_station%2C_2024_%281%29.jpg/1920px-S%C3%A3o_Joaquim_metro_station%2C_2024_%281%29.jpg', 'Jcornelius', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:S%C3%A3o_Joaquim_metro_station,_2024_(1).jpg'),
  ('serra-do-corvo-branco', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Serra_do_Corvo_Branco_-_Gr%C3%A3o_Para_SC_-_panoramio.jpg/1920px-Serra_do_Corvo_Branco_-_Gr%C3%A3o_Para_SC_-_panoramio.jpg', 'caetano051068', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Serra_do_Corvo_Branco_-_Gr%C3%A3o_Para_SC_-_panoramio.jpg'),
  ('serra-do-rio-do-rastro', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Serra_do_Rio_do_Rastro%2C_Bom_Jardim_da_Serra_-_panoramio.jpg/1920px-Serra_do_Rio_do_Rastro%2C_Bom_Jardim_da_Serra_-_panoramio.jpg', 'Vinicius Lannes Duer…', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Serra_do_Rio_do_Rastro,_Bom_Jardim_da_Serra_-_panoramio.jpg'),
  ('serra-dona-francisca', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/%C3%81rea_de_Prote%C3%A7%C3%A3o_Ambiental_Serra_Dona_Francisca_-_Luiz_Alves_%2812%29.jpg/1920px-%C3%81rea_de_Prote%C3%A7%C3%A3o_Ambiental_Serra_Dona_Francisca_-_Luiz_Alves_%2812%29.jpg', 'Luizalves1990', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:%C3%81rea_de_Prote%C3%A7%C3%A3o_Ambiental_Serra_Dona_Francisca_-_Luiz_Alves_(12).jpg'),
  ('urubici', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Urubici_Waterfall.jpg/1920px-Urubici_Waterfall.jpg', 'Catarinaf7', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Urubici_Waterfall.jpg'),
  ('urupema', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Urupema._A_cidade_mais_fria_do_Brasil.jpg/1920px-Urupema._A_cidade_mais_fria_do_Brasil.jpg', 'Carlos.eduardon', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Urupema._A_cidade_mais_fria_do_Brasil.jpg')
) as novo (slug, url, autor, licenca, origem)
where p.slug = novo.slug;
